### ISSUE TITLE
submitGetFDTokenForCreditCard fails for missing transaction_type

### ISSUE THREAD

**Issue by ghost** [payeezy/payeezy_ios#7]
Here is request info and error response on sandbox environment:

Request: {"ta_token":"NOIW","type":"FDToken","credit_card":{"card_number":"4111111111111111","exp_date":"0118","cardholder_name":"M M M","type":"Visa","cvv":"123"},"auth":"false"}

(lldb) po errorObject
{
Error = {
messages = (
{
code = "missing_transaction_type";
description = "The transaction type is missing";
}
);
};
"correlation_id" = "228.1475788157148";
"transaction_status" = "Not Processed";
"validation_status" = failed;
}

submitGetFDTokenForCreditCard does not have a transaction_type parameter, so how do I add it?

**Comment by ywalterh** [comment]
Hey @scott4arrows Could you share how you resolved this issue? I'm facing something similar and confused.

**Comment by ghost** [comment]
@walterhuangfs I don't remember if I did. We dropped payeezy for other reasons and moved to a different payment provider.
